### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json

{
  "title": "GO to gym today",
  "date": "2021-01-01T12:00:00Z",
  "description": "Sushil GO to gym yaar",
  "priority": "normal",
  "status": "todo"
}

### Update a new task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
  "id":"127acf28-aa65-4769-892d-e195c955680f",
  "status": "inProgress"
}